const CONTINENTS = {
  NA: [
    'AG',
    'BS',
    'BB',
    'BZ',
    'CA',
    'CR',
    'CU',
    'DM',
    'DO',
    'SV',
    'GD',
    'GT',
    'HT',
    'HN',
    'JM',
    'MX',
    'NI',
    'PA',
    'KN',
    'LC',
    'VC',
    'TT',
    'US',
  ],
  SA: [
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
  ],
  AF: {},
  EU: {},
  AS: {},
  OC: {},
}

module.exports = CONTINENTS;

/*
'Antigue and Barbuda': {},
    'Bahamas': {},
    'Barbados': {},
    'Belize': {},
    'Canada': {},
    'Costa Rica': {},
    'Cuba': {},
    'Dominica': {},
    'Dominican Republic': {},
    'El Salvador': {},
    'Grenada': {},
    'Guatemala': {},
    'Haiti': {},
    'Honduras': {},
    'Jamaica': {},
    'Mexico': {},
    'Nicaragua': {},
    'Panama': {},
    'Saint Kitts and Nevis': {},
    'Saint Lucia': {},
    'Saint Vincent and the Grenadines': {},
    'Trinidad and Tobago': {},
    'United States of America': {},
    SA: {
    'Argentina': {},
    'Bolivia': {},
    'Brazil': {},
    'Chile': {},
    'Colombia': {},
    'Ecuador': {},
    'Guyana': {},
    'Paraguay': {},
    'Peru': {},
    'Suriname': {},
    'Uruguay': {},
    'Venezuela': {},
  },
*/